### ISSUE TITLE
SIGSEGV when running basic example

### ISSUE THREAD

**Issue by jtyr** [malarinv/terraform-provider-gitea#5]
I was hoping to use this provider to provision Gitea orgs and repos. But unfortunately with the following example:

```terraform
terraform {
  required_providers {
    gitea = {
      source  = "malarinv/gitea"
      version = "~> 0.3.0"
    }
  }
}

provider "gitea" {
  base_url = var.base_url
  insecure = true
  username = var.username
  password = var.password
}

resource "gitea_org" "gitops" {
  name = "gitops"
}

resource "gitea_repository" "test" {
  name     = "test"
  username = gitea_org.gitops.name
}
```

I'm getting this error:

```
$ terraform apply
╷
│ Error: Plugin did not respond
│ 
│   with provider["registry.terraform.io/malarinv/gitea"],
│   on main.tf line 10, in provider "gitea":
│   10: provider "gitea" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-gitea_v0.3.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x90 pc=0x6e4d1e]

goroutine 8 [running]:
code.gitea.io/sdk/gitea.(*Client).doRequest(0x0, {0xd300fa, 0x3}, {0xd30f71, 0x5}, 0x0, {0x0, 0x0})
	code.gitea.io/sdk/gitea@v0.15.1/client.go:206 +0x7e
code.gitea.io/sdk/gitea.(*Client).getResponse(0x1417fe0, {0xd300fa, 0x0}, {0xd30f71, 0xc0004f5870}, 0x40d247, {0x0, 0x0})
	code.gitea.io/sdk/gitea@v0.15.1/client.go:289 +0x7d
code.gitea.io/sdk/gitea.(*Client).getParsedResponse(0xc0001e2390, {0xd300fa, 0x6e3f26}, {0xd30f71, 0xc0000c6280}, 0xc0004f5801, {0x0, 0x0}, {0xbdd480, 0xc00046a0f0})
	code.gitea.io/sdk/gitea@v0.15.1/client.go:311 +0x36
code.gitea.io/sdk/gitea.(*Client).GetMyUserInfo(0xc000179d70)
	code.gitea.io/sdk/gitea@v0.15.1/user.go:67 +0x65
code.gitea.io/terraform-provider-gitea/gitea.(*Config).Client(0xc0004f5a20)
	code.gitea.io/terraform-provider-gitea/gitea/config.go:72 +0x3e5
code.gitea.io/terraform-provider-gitea/gitea.providerConfigure(0xc00007c240)
	code.gitea.io/terraform-provider-gitea/gitea/provider.go:111 +0x245
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Configure(0xc0004aa000, 0xc0001de0e0)
	github.com/hashicorp/terraform-plugin-sdk@v1.13.0/helper/schema/provider.go:275 +0xb4
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).Configure(0xc00000e030, {0xc0001dc080, 0x586766}, 0xc0001dc080)
	github.com/hashicorp/terraform-plugin-sdk@v1.13.0/internal/helper/plugin/grpc_provider.go:487 +0x1d2
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_Configure_Handler({0xd06740, 0xc00000e030}, {0xea95b0, 0xc000197b30}, 0xc0000183c0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.13.0/internal/tfplugin5/tfplugin5.pb.go:3251 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000160480, {0xeb7448, 0xc000160600}, 0xc00001c200, 0xc00007cff0, 0x1409318, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc000160480, {0xeb7448, 0xc000160600}, 0xc00001c200, 0x0)
	google.golang.org/grpc@v1.27.1/server.go:1313 +0xa56
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.1/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.1/server.go:720 +0xef

Error: The terraform-provider-gitea_v0.3.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Any idea what could be wrong?

**Comment by Lerentis** [comment]
Hi @jtyr ,

seems to be related to the gitea client creation. could you try it again with token authentication and check if this works? Also if you could share a little about your setup if we could recreate it for testing purposes that would help :) 

also you might want to check if this error persits with [my fork](https://github.com/Lerentis/terraform-provider-gitea) as i continues development there a little

**Comment by jtyr** [comment]
Unfortunately I don't know how to create a token in the web UI. I have installed Gitea on a local [K3D](https://k3d.io/) cluster like this:

```shell
k3d cluster create test1 -p '80:80@loadbalancer' -p '443:443@loadbalancer'
helm repo add gitea https://dl.gitea.io/charts
cat <<END | helm upgrade --install --namespace gitea --create-namespace --wait --values - gitea/gitea
image:
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  hosts:
    - host: git.localhost
      paths:
        - path: /
          pathType: Prefix

persistence:
  size: 1Gi

postgresql:
  enabled: false

memcached:
  enabled: false

gitea:
  config:
    database:
      DB_TYPE: sqlite3
    server:
      SSH_DOMAIN: localhost
      SSH_PORT: 2222
  admin:
    username: gitea_admin
    password: myadmin
    email: admin@git.localhost
END
```

Then you can access the Web UI via http://git.localhost.

Btw. I'm getting the same error with the provider from your [fork](https://registry.terraform.io/providers/Lerentis/gitea/latest).

**Comment by Lerentis** [comment]
thanks 👍  i will try to reproduce this. 
you can create a token in your profile -> settings -> applications

**Comment by jtyr** [comment]
Thanks for the hint where to create the token. I have created one and I'm still getting the same error.

**Comment by Lerentis** [comment]
i am able to reproduce this with a build from the registry but not with a local dev build. can you try to build the provider locally and reference it? 
There is a Makefile in this repository, so if you have go installed, you should be able to run `make install` to build and install the provider locally. afterwards you can change the source to `source = "terraform.local/local/gitea"`

i guess this is somehow related to the goreleaser build and the `.localhost` TLD. on a local docker image URL (`http://localhost:3000`) as well as with a real TLD the build from the registry works fine

**Comment by jtyr** [comment]
Thanks for testing it. I can confirm that the problem is the TLD. All seems to work when I add this into my `/etc/hosts`:

```
127.0.0.1       localhost git.localhost
```

It would be great if the provider would crash with some more meaningful message tho ;o)

**Comment by Lerentis** [comment]
i could write a more explicit failure message indeed, but to be fair here a subdomain for localhost already violates [RFC 2606](https://datatracker.ietf.org/doc/html/rfc2606).

With all the information here i would consider this issue as closed now. feel free to reopen if you disagree or open a new issue if you encounter anything else 😃
